//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YapayZekaTemelleri
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPRODUCT
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BRAND { get; set; }
        public Nullable<short> STOCK { get; set; }
        public Nullable<decimal> BUYPRICE { get; set; }
        public Nullable<decimal> SELLPRICE { get; set; }
        public string CATEGORY { get; set; }
        public Nullable<System.DateTime> DATEADDPRO { get; set; }
        public Nullable<bool> PRODUCTCASE { get; set; }
    }
}
